server:
  port: ${{SERVER_PORT}:20001}
  tomcat:
    uri-encoding: UTF-8
  context-path: /ccb-api

management:
  port: ${{MANAGEMENT_PORT}:20002}

endpoints:
  health:
    sensitive: false
  shutdown:
    sensitive: true
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://192.168.118.8:23306/winstar-cbc-platform?characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 1900000
      maximum-pool-size: 10
  redis:
    database: 7
    host: 192.168.118.111
    port: 6379
    password:
    pool.max-active: 1000
    pool.max-wait: -1
    pool.max-idle: 8
    pool.min-idle: 0
    timeout: 10000
  kafka:
    producer:
      acks: -1
      batch-size: 10
    template:
      default-topic: order_success_message
    bootstrap-servers: 192.168.118.69:9092
    consumer:
      group-id: myGroup
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: MANUAL_IMMEDIATE
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
  profiles: default

info:
  cardUrl: https://wanglt.easy-pass.cn/webservice/services/SvcService
  cardUrl_new: http://ticket.api.muiyou.com/shellCoupons/services/SvcService
  profilesActive: false
  flowUrl: http://192.168.118.7:2300/api/v1/flow/order
  amount: 100
  getTokenInfoUrl: http://winstar.api.sxeccellentdriving.com/winstar-api/api/user/account/{userId}/{type}/getTokenInfo
  getLocalCarsUrl: http://winstar.api.sxeccellentdriving.com/winstar-api/api/user/vehicle/getUserVehicleWechat
  getSixInOneCarsUrl: http://mobile.sxwinstar.net/wechat_access/api/v1/platenumbers/certificateNumberTypeSearch?certificateNumber={certificateNumber}&&certificateType={certificateType}
  sendMsgUrl: http://sms.sxjiashi.com:8080/api/v2/smsSend/sendNotice
  checkBindLicense: https://mobile.sxwinstar.net/wechat_access/api/user/auth/checkBindLicense
  authDriverLicense: https://mobile.sxwinstar.net/wechat_access/api/user/auth/auth
  coupon_recover_switch: false
#  cost_exchange_server: http://192.168.118.54:11020/
  cost_exchange_server: http://192.168.118.104:11020/
  communal_coupon_server: http://192.168.118.129:12002/
  takeCouponUrl: ${info.communal_coupon_server}api/v1/coupon/takeCoupons?
  verifyCouponUrl: ${info.communal_coupon_server}api/v1/coupon/verify/verify?
  writeOffCouponUrl: ${info.communal_coupon_server}api/v1/coupon/verify/cancel
  getTemplateInfoUrl: ${info.communal_coupon_server}api/v1/coupon/template?
  handleBusinessUrl: ${info.cost_exchange_server}api/v1/phonebill/giving/handleBusiness
  phoneNumberCheckUrl: ${info.cost_exchange_server}api/v1/phonebill/giving/phoneValidate
  sendCodeUrl: ${info.cost_exchange_server}api/v1/phonebill/giving/sendVerifyCode
pay:
  wx:
     base:
        access-token-url: http://wechat.sxeccellentdriving.com/php-api/wechat_front/ccb/ccb-php/index.php?type=api&fun=getAccessToken_f80863bc_9177_11e6_a05e_9457a5545c84
     jsapi:
          sign-key: FAmvMI8ARjOhqJTE3vL5d87mFo9VIbDN
          app-secret: 43dd74d136a23e8467e5866f4757a3ec
          app-id: wx47a21bee64eb7a6c
          mch-id: 1504450061

#建行信息卡校验
bank:
  sms:
    sendVerifyCodeUrl:  ${{SEND_VERIFY_CODE}:http://113.140.28.230:5080/AuthPlatform/rest/auth/sendAuth}
    checkVerifyCodeUrl: ${{CHECK_VERIFY_CODE}:http://113.140.28.230:5080/AuthPlatform/rest/auth/auth}
    user: ${{BBC_SMS_USER}:test}
    pwd:  ${{BBC_SMS_PWD}:test}

#万盛达验证码验证
verify_sms_url: http://sms.sxjiashi.com:8080/api/v2/smsSend/{id}/id/{verifyCode}/verifyCode/{phoneNumber}/phoneNumber
#发送验证码
send_sms_url: http://sms.sxjiashi.com:8080/api/v2/smsSend/{phoneNumber}/phoneNumber/1/types/
#获取图片验证码
get_random_image_code: http://sms.sxjiashi.com:8080/api/v4/smsSend/getRandomCode
#验证图片验证码
send_sms_image_url: http://sms.sxjiashi.com:8080/api/v4/smsSend/send

activity_id_fission: 3d15c8ca-83e4-11e8-80dd-9457a5545c84
---
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 1900000
      maximum-pool-size: 1000
  redis:
    database: 7
    host: 10.0.20.165
    port: 6379
    password:
    pool.max-active: -1
    pool.max-wait: -1
    pool.max-idle: 8
    pool.min-idle: 0
    timeout: 10000
  kafka:
    producer:
      acks: -1
      batch-size: 10
    template:
      default-topic: order_success_message
    bootstrap-servers: ${KAFKA_SERVERS}
    consumer:
      group-id: myGroup
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: MANUAL_IMMEDIATE
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  profiles: prod

server:
  port: ${{SERVER_PORT}:8080}

management:
  port: ${{MANAGEMENT_PORT}:8081}

endpoints:
  health:
    sensitive: false
  shutdown:
    sensitive: true

info:
  cardUrl: https://coupons.easy-pass.cn/shellCoupons/services/SvcService
  cardUrl_new: http://ticket.api.muiyou.com/shellCoupons/services/SvcService
  profilesActive: true
  flowUrl: http://api.sxwinstar.net/flow/api/v1/flow/order
  amount: 100
  getTokenInfoUrl: http://mobile.sxwinstar.net/wechat_access/api/user/account/{userId}/{type}/getTokenInfo
  getLocalCarsUrl: http://mobile.sxwinstar.net/wechat_access/api/user/vehicle/getUserVehicleWechat
  getSixInOneCarsUrl: http://mobile.sxwinstar.net/wechat_access/api/v1/platenumbers/certificateNumberTypeSearch?certificateNumber={certificateNumber}&&certificateType={certificateType}
  sendMsgUrl: http://sms.sxjiashi.com:8030/api/v2/smsSend/sendNotice
  checkBindLicense: https://mobile.sxwinstar.net/wechat_access/api/user/auth/checkBindLicense
  authDriverLicense: https://mobile.sxwinstar.net/wechat_access/api/user/auth/auth
  coupon_recover_switch: ${couponRecoverSwitch}
  cost_exchange_server: ${costExchangeServer}
  communal_coupon_server: ${communalCouponServer}
  takeCouponUrl: ${info.communal_coupon_server}api/v1/coupon/takeCoupons?
  verifyCouponUrl: ${info.communal_coupon_server}api/v1/coupon/verify/verify?
  writeOffCouponUrl: ${info.communal_coupon_server}api/v1/coupon/verify/cancel
  getTemplateInfoUrl: ${info.communal_coupon_server}api/v1/coupon/template?
  handleBusinessUrl: ${info.cost_exchange_server}api/v1/phonebill/giving/handleBusiness
  phoneNumberCheckUrl: ${info.cost_exchange_server}api/v1/phonebill/giving/phoneValidate
  sendCodeUrl: ${info.cost_exchange_server}api/v1/phonebill/giving/sendVerifyCode
#建行信息卡校验
bank:
  sms:
    sendVerifyCodeUrl:  ${{SEND_VERIFY_CODE}:http://113.140.28.230:5080/AuthPlatform/rest/auth/sendAuth}
    checkVerifyCodeUrl: ${{CHECK_VERIFY_CODE}:http://113.140.28.230:5080/AuthPlatform/rest/auth/auth}
    user: ${{BBC_SMS_USER}:test}
    pwd:  ${{BBC_SMS_PWD}:test}

#万盛达验证码验证
verify_sms_url: http://sms.sxjiashi.com:8030/api/v2/smsSend/{id}/id/{verifyCode}/verifyCode/{phoneNumber}/phoneNumber
#发送验证码
send_sms_url: http://sms.sxjiashi.com:8030/api/v2/smsSend/{phoneNumber}/phoneNumber/1/types/
#获取图片验证码
get_random_image_code: http://sms.sxjiashi.com:8030/api/v4/smsSend/getRandomCode
#验证图片验证码
send_sms_image_url: http://sms.sxjiashi.com:8030/api/v4/smsSend/send

activity_id_fission: 3d15c8ca-83e4-11e8-80dd-9457a5545c84

pay:
  wx:
     base:
        access-token-url: https://mobile.sxwinstar.net/wechat/index.php?type=api&fun=getAccessToken_f80863bc_9177_11e6_a05e_9457a5545c84
     jsapi:
        signKey: B793c5IPBC7B9wFQ5p55JFpx37S3iNRy
        mch-id: 1249655701
        app-id: wxcf71d6832b8e3ebe
        app-secret: 9401a98f94e021d3f006c3831f8d0e05
