server:
  port: ${{SERVER_PORT}:20001}

management:
  port: ${{MANAGEMENT_PORT}:20002}

endpoints:
  health:
    sensitive: false
  shutdown:
    sensitive: true
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://192.168.118.8:23306/winstar-cbc-platform?characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 1900000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  profiles: default

info:
  cardUrl: https://coupons.easy-pass.cn/shellCoupons/services/SvcService
  profilesActive: false
  flowUrl: http://192.168.118.7:2300/api/v1/flow/order
  amount: 100
#建行信息卡校验
bank:
  sms:
    sendVerifyCodeUrl:  ${{SEND_VERIFY_CODE}:http://113.140.28.230:5080/AuthPlatform/rest/auth/sendAuth}
    checkVerifyCodeUrl: ${{CHECK_VERIFY_CODE}:http://113.140.28.230:5080/AuthPlatform/rest/auth/auth}
    user: ${{BBC_SMS_USER}:test}
    pwd:  ${{BBC_SMS_PWD}:test}

---
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 1900000
      maximum-pool-size: 500
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  profiles: prod

server:
  port: ${{SERVER_PORT}:8080}

management:
  port: ${{MANAGEMENT_PORT}:8081}

endpoints:
  health:
    sensitive: false
  shutdown:
    sensitive: true

info:
  cardUrl: https://coupons.easy-pass.cn/shellCoupons/services/SvcService
  profilesActive: true
  flowUrl: http://api.sxwinstar.net/flow/api/v1/flow/order
  amount: 100

#建行信息卡校验
bank:
  sms:
    sendVerifyCodeUrl:  ${{SEND_VERIFY_CODE}:http://113.140.28.230:5080/AuthPlatform/rest/auth/sendAuth}
    checkVerifyCodeUrl: ${{CHECK_VERIFY_CODE}:http://113.140.28.230:5080/AuthPlatform/rest/auth/auth}
    user: ${{BBC_SMS_USER}:test}
    pwd:  ${{BBC_SMS_PWD}:test}
