package ws.server;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-23T15:48:30.580+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "SvcService", 
                  wsdlLocation = "http://111.20.145.94:18070/webservice/services/SvcService?wsdl",
                  targetNamespace = "http://server.ws") 
public class SvcService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.ws", "SvcService");
    public final static QName SvcServiceHttpPort = new QName("http://server.ws", "SvcServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://111.20.145.94:18070/webservice/services/SvcService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SvcService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://111.20.145.94:18070/webservice/services/SvcService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SvcService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SvcService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SvcService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SvcService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SvcService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SvcService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SvcServicePortType
     */
    @WebEndpoint(name = "SvcServiceHttpPort")
    public SvcServicePortType getSvcServiceHttpPort() {
        return super.getPort(SvcServiceHttpPort, SvcServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SvcServicePortType
     */
    @WebEndpoint(name = "SvcServiceHttpPort")
    public SvcServicePortType getSvcServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(SvcServiceHttpPort, SvcServicePortType.class, features);
    }

}
