
package ws.server;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-23T15:48:30.542+08:00
 * Generated source version: 3.1.11
 * 
 */
public final class SvcServicePortType_SvcServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.ws", "SvcService");

    private SvcServicePortType_SvcServiceHttpPort_Client() {
    }

  /*  public static void main(String args[]) throws Exception {
        URL wsdlURL = SvcService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SvcService ss = new SvcService(wsdlURL, SERVICE_NAME);
        SvcServicePortType port = ss.getSvcServiceHttpPort();  
        
        {
        System.out.println("Invoking transX...");
        ws.object.SvcInfo _transX_in0 = null;
        ws.object.SvcInfo _transX__return = port.transX(_transX_in0);
        System.out.println("transX.result=" + _transX__return);


        }
        {
        System.out.println("Invoking searchTrans...");
        ws.object.TransReq _searchTrans_in0 = null;
        ws.object.SvcResp _searchTrans__return = port.searchTrans(_searchTrans_in0);
        System.out.println("searchTrans.result=" + _searchTrans__return);


        }
        {
        System.out.println("Invoking searchMchInfo...");
        ws.object.TransReq _searchMchInfo_in0 = null;
        ws.object.SvcResp _searchMchInfo__return = port.searchMchInfo(_searchMchInfo_in0);
        System.out.println("searchMchInfo.result=" + _searchMchInfo__return);


        }

        System.exit(0);
    }
*/
}
