@startuml
(*) -->"处理违法"
(*) -->"首页"
If "选择活动"
--> "折中折"
--> "商品"
else
--> "赠券活动"
--> "商品"
    If "判断商品所属活动类型"  then
        -->[折中折活动] "CBC支付"
        -->"我的订单"
    else
        -->[一元券抢购] "查询购买权限"
        If "查询购买权限" then
           -->[有权限已使用] "提示：用户只能购买1次"
         else
              -->[无权限] "处理违法"
                    If "" then
                        -->[首次使用建行信用卡缴罚的用户] "首页"
                    else
                        -->[非首次使用建行信用卡缴罚的用户] "不做处理"
                    EndIf
         else
              -->[有权限未使用] "CBC支付"

        EndIf
    else
        -->[赠券活动] "查询可用优惠券"
        -->"微信支付"
        -->"赠送优惠券"
        -->"我的订单"
    EndIf


EndIf
@enduml